import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';
import { Header } from './components/SimpleHeader/Header';
import { SimpleFooter } from './components/SimpleFooter/SimpleFooter';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider defaultColorScheme="dark">
          <Header />
          {children}
          <SimpleFooter />
        </MantineProvider>
      </body>
    </html>
  );
}
